UI/UI/Areas/Admin/Controllers/LessonController.cs
using Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Utility;

namespace UI.Areas.Admin.Controllers
{
    public class LessonController : Controller
    {
        EduContext db = new EduContext();

        // GET: Admin/Lesson
        public ActionResult Index(int? id)
        {
            List<Lesson> lessons = db.Lessons.Where(x => x.EducationID == id).ToList();
            return View(lessons);
        }
        public ActionResult Index2(Category cat)
        {
            List<Lesson> lessons = db.Lessons.Where(x => cat.ID == cat.ID).ToList();
            return View();
        }
        public ActionResult Index3(Category cat)
        {
            List<Lesson> lessons = db.Lessons.Where(x => x.CategoryID == cat.ID).ToList();
            return View(lessons);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Lesson data, HttpPostedFileBase Image, HttpPostedFileBase Pdf)
        {
            Lesson yeni = new Lesson();
            yeni.Logo = ImageUploader.UploadSingleImage("/Uploads/", Image);
            yeni.Content = PdfUploader.UploadPdf("/UploadContent/", Pdf);
            yeni.UnitID = data.UnitID;
            yeni.EducationID = data.EducationID;
            yeni.CategoryID = data.CategoryID;
            yeni.Name = data.Name;
            //yeni.Logo = data.Logo;
            yeni.StartDate = data.StartDate;
            yeni.EndDate = data.EndDate;
            yeni.Path = data.Path;
            yeni.TeacherID = data.TeacherID;
            yeni.IsLive = false;
            yeni.ExamLink = data.ExamLink;
            //yeni.Content = data.Content;
            db.Lessons.Add(yeni);
            db.SaveChanges();
            return RedirectToAction("Index2");
        }
        [HttpGet]
        public ActionResult Update(int id)
        {
            Lesson updLesson = db.Lessons.Find(id);
            return View(updLesson);
        }
        [HttpPost]
        public ActionResult Update(Lesson data, HttpPostedFileBase Image, HttpPostedFileBase Pdf)
        {
            Lesson updLesson = db.Lessons.Find(data.ID);

            if (Pdf != null)
            {
                data.Content = PdfUploader.UploadPdf("/UploadContent/", Pdf);

            }
            else
            {
                data.Content = updLesson.Content;
            }

            if (Image != null)
            {
                data.Logo = ImageUploader.UploadSingleImage("/Uploads/", Image);
            }
            else
            {
                data.Logo = updLesson.Logo;
            }

            updLesson.Name = data.Name;
            updLesson.TeacherID = data.TeacherID;
            updLesson.EducationID = data.EducationID;
            updLesson.StartDate = data.StartDate;
            updLesson.EndDate = data.EndDate;
            updLesson.Path = data.Path;
            updLesson.Content = data.Content;
            updLesson.Logo = data.Logo;
            updLesson.CategoryID = data.CategoryID;
            updLesson.UnitID = data.UnitID;

            updLesson.ExamLink = data.ExamLink;          

            db.SaveChanges();
            return RedirectToAction("Index2");
        }

        public ActionResult Delete(int id)
        {
            Lesson delLesson = db.Lessons.Find(id);
            db.Lessons.Remove(delLesson);
            db.SaveChanges();
            return RedirectToAction("Index2");
        }

        public JsonResult GetUnitsByEducationId(int id)
        {
            Education education = db.Educations.Find(id);
            var jsonData = from u in education.Units
                           select new
                           {
                               ID = u.ID,
                               Name = u.Name
                           };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }
    }
}

UI/UI/Areas/Admin/Controllers/StudentController.cs
using Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Areas.Admin.Controllers
{
    public class StudentController : Controller
    {
        EduContext db = new EduContext();
        // GET: Admin/Student
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Entity.Student data)
        {
            db.Students.Add(data);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Update(int id)
        {
            Entity.Student updStudent = db.Students.Find(id);
            return View(updStudent);
        }
        [HttpPost]
        public ActionResult Update(Entity.Student data, string[] categories)
        {
            Entity.Student updStudent = db.Students.Find(data.ID);
            updStudent.FirstName = data.FirstName;
            updStudent.LastName = data.LastName;
            updStudent.Email = data.Email;
            updStudent.Password = data.Password;
            updStudent.PhoneNumber = data.PhoneNumber;
            updStudent.School = data.School;
            updStudent.Grade = data.Grade;
            updStudent.Categories.Clear();
            
            db.SaveChanges();
            foreach (string cat in categories)
            {
                int catId = Convert.ToInt32(cat);
                Category category = db.Categories.Find(catId);
                updStudent.Categories.Add(category);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            Entity.Student delStudent = db.Students.Find(id);
            db.Students.Remove(delStudent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult ToClassroom(int id)
        {
            Entity.Student student = db.Students.Find(id);
            return View(student);
        }
        [HttpPost]
        public ActionResult ToClassroom(int id, int categoryID)
        {
            Entity.Category category = db.Categories.Find(categoryID);
            Entity.Student student = db.Students.Find(id);
            student.Categories.Add(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

UI/UI/Areas/Admin/Controllers/TeacherController.cs
using Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Utility;

namespace UI.Areas.Admin.Controllers
{
    public class TeacherController : Controller
    {
        EduContext db = new EduContext();
        // GET: Admin/Teacher
     
        public ActionResult Index()
        {
            return View();
        }
       
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Teacher data, HttpPostedFileBase Image)
        {
            Teacher yeni = new Teacher();
            yeni.Detail = ImageUploader.UploadSingleImage("/Uploads/", Image);

            yeni.FirstName = data.FirstName;
            yeni.LastName = data.LastName;
            yeni.Email = data.Email;
            yeni.Password = data.Password;
            yeni.Phone = data.Phone;
            yeni.Address = data.Address;      
            yeni.Note = data.Note;

            db.Teachers.Add(yeni);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Update(int id)
        {
            Teacher updTeacher = db.Teachers.Find(id);
            return View(updTeacher);
        }
        [HttpPost]
        public ActionResult Update(Teacher data, HttpPostedFileBase Image)
        {
            Teacher updTeacher = db.Teachers.Find(data.ID);
            if (Image!=null)
            {
                data.Detail = ImageUploader.UploadSingleImage("/Uploads/", Image);
            }
            else
            {
                data.Detail = updTeacher.Detail;
            }

            updTeacher.Detail = data.Detail;
            updTeacher.FirstName = data.FirstName;
            updTeacher.LastName = data.LastName;
            updTeacher.Email = data.Email;
            updTeacher.Password = data.Password;
            updTeacher.Phone = data.Phone;
            updTeacher.Address = data.Address;
            updTeacher.Note = data.Note;

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            Teacher delTeacher = db.Teachers.Find(id);
            db.Teachers.Remove(delTeacher);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

UI/UI/Areas/Admin/Controllers/UnitController.cs
using Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Areas.Admin.Controllers
{
    public class UnitController : Controller
    {
        EduContext db = new EduContext();
        // GET: Admin/Unit
        public ActionResult Index(int? id)
        {
            List<Lesson> lessons = db.Lessons.Where(x => x.EducationID == id).OrderBy(x => x.EducationID).ToList();
            return View(lessons);
        }
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Unit data)
        {
            Unit yeni = new Unit();
            yeni.Name = data.Name;
            yeni.EducationID = data.EducationID;

            db.Units.Add(yeni);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Update(int? id)
        {
            Unit updUnit = db.Units.Find(id);
            return View(updUnit);
        }
        [HttpPost]
        public ActionResult Update(Unit data)
        {
            Unit updUnit = db.Units.Find(data.ID);
            updUnit.Name = data.Name;
            updUnit.EducationID = data.EducationID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            Unit delUnit = db.Units.Find(id);
            db.Units.Remove(delUnit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

UI/UI/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@using Entity
@{
    List<Education> educations = Query.EducationList();
    Admin currentAdmin = Session["currentAdmin"] as Admin;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/Areas/Admin/Content/img/logo.png">
    <link rel="icon" type="image/png" href="~/Areas/Admin/Content/img/logo.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        @ViewBag.Title
    </title>
    <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link href="~/Areas/Admin/Content/css/material-dashboard.css?v=2.1.2" rel="stylesheet" />
    <link href="~/Areas/Admin/Content/demo/demo.css" rel="stylesheet" />
</head>

<body class="">
    <div class="wrapper ">
        <div class="sidebar" data-color="purple" data-background-color="white" data-image="~/Areas/Admin/Content/img/sidebar-1.jpg">
            <div class="logo">
                <a href="" class="simple-text logo-normal">
                    <img src="~/Areas/Admin/Content/img/logo.png" alt="" height="50px;" width="70px;">
                    <h6></h6>
                    <h4><b>BİLİM VE TEKNOLOJİ <br />OKULU </b></h4>
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li class="nav-item active  ">
                        <a class="nav-link" href="@Url.Action("Index","Home", new { area = "Admin" })">
                            <i class="material-icons">dashboard</i>
                            <p>Anasayfa</p>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="@Url.Action("Index","Category", new { area = "Admin" })">
                            <i class="material-icons">content_paste</i>
                            <p>Sınıflar</p>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="@Url.Action("Index","Education", new { area = "Admin" })">
                            <i class="material-icons">content_paste</i>
                            <p>Eğitimler</p>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="@Url.Action("Index2","Lesson", new { area = "Admin" })">
                            <i class="material-icons">content_paste</i>
                            <p>Dersler</p>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="@Url.Action("Index","Unit", new { area = "Admin" })">
                            <i class="material-icons">content_paste</i>
                            <p>Üniteler</p>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="@Url.Action("Index","Teacher", new { area = "Admin" })">
                            <i class="material-icons">content_paste</i>
                            <p>Öğretmenler</p>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="@Url.Action("Index","Student", new { area = "Admin" })">
                            <i class="material-icons">content_paste</i>
                            <p>Öğrenciler</p>
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="@Url.Action("AdminList","Home", new { area = "Admin" })">
                            <i class="material-icons">content_paste</i>
                            <p>Adminler</p>
                        </a>
                    </li>

                </ul>
            </div>
        </div>
        <div class="main-panel">
            <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-md-start">
                        <span class="title"><b>Hoşgeldiniz Sn. @currentAdmin.FirstName.ToUpper() @currentAdmin.LastName.ToUpper()</b></span>
                    </div>
                    <div class="collapse navbar-collapse justify-content-end">
                        <ul class="navbar-nav">
                            <li class="nav-item btn-rotate dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Çıkış Yap
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="@Url.Action("Logout","Account",new {area="" })">Çıkış Yap</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            @RenderBody()
            <footer class="footer">
                <div class="container-fluid">
                    <div class="copyright float-right">
                        &copy;
                        <script>
                            document.write(new Date().getFullYear())
                        </script>, made with by
                        <a>Ayşe TOKTAŞ & Mustafa Umut AVCI</a>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/Areas/Admin/Content/js/core/jquery.min.js"></script>
    <script src="~/Areas/Admin/Content/js/core/popper.min.js"></script>
    <script src="~/Areas/Admin/Content/js/core/bootstrap-material-design.min.js"></script>
    <script src="~/Areas/Admin/Content/js/plugins/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/Areas/Admin/Content/js/plugins/moment.min.js"></script>
    <script src="~/Areas/Admin/Content/js/plugins/sweetalert2.js"></script>
    <script src="~/Areas/Admin/Content/js/plugins/jquery.validate.min.js"></script>
    <script src="~/Areas/Admin/Content/js/plugins/jquery.bootstrap-wizard.js"></script>
    <script src="~/Areas/Admin/Content/js/plugins/bootstrap-selectpicker.js"></script>
    <script src="~/Areas/Admin/Content/js/plugins/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Areas/Admin/Content/js/plugins/jquery.dataTables.min.js"></script>
    <script src="~/Areas/Admin/Content/js/plugins/bootstrap-tagsinput.js"></script>
    <script src="~/Areas/Admin/Content/js/plugins/jasny-bootstrap.min.js"></script>
    <script src="~/Areas/Admin/Content/js/plugins/fullcalendar.min.js"></script>
    <script src="~/Areas/Admin/Content/js/plugins/jquery-jvectormap.js"></script>
    <script src="~/Areas/Admin/Content/js/plugins/nouislider.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
    <script src="~/Areas/Admin/Content/js/plugins/arrive.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
    <script src="~/Areas/Admin/Content/js/plugins/chartist.min.js"></script>
    <script src="~/Areas/Admin/Content/js/plugins/bootstrap-notify.js"></script>
    <script src="~/Areas/Admin/Content/js/material-dashboard.js?v=2.1.2" type="text/javascript"></script>
    <script src="~/Areas/Admin/Content/demo/demo.js"></script>
    <script src="~/Areas/Admin/Content/js/CustomScript.js"></script>

    <!--Datatable-->
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedcolumns/3.3.2/css/fixedColumns.dataTables.min.css" />
    <script type="text/javascript" src="//cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/fixedcolumns/3.3.2/js/dataTables.fixedColumns.min.js"></script>


    <script type="text/javascript">
        $(document).ready(function () {
            $('#eduLessonTable').DataTable();
            $('#educationTable').DataTable();
            $('#teacherTable').DataTable({
                "autoWidth": false,
                "columnDefs": [
                    { "width": "20%", "targets": 0 }
                ]
            });
            $('#studentTable').DataTable({
                "autoWidth": false,
                "columnDefs": [
                    { "width": "20%", "targets": 0 }
                ]
            });
            $('#categoryTable').DataTable();
            $('#unitTable').DataTable();
            $('#adminTable').DataTable();



        });
    </script>
</body>
</html>